### ISSUE TITLE
Message passing

### ISSUE THREAD

**Issue by IsaacWoods** [IsaacWoods/pebble#28]
### Format
- [ ] Decide how to do chars (probably just hardcode as 4 bytes long)
- [ ] Decide on format for dynamically sized elements (potential message size savings vs. simplicity)
- [ ] Document the format

### Serialization and deserialization
- [ ] Write serializer
- [ ] Write deserializer
- [ ] Write test suite for well-formed and malformed messages (can run on host)
- [ ] Write fuzzer (can run on host)

### Kernel and userspace
- [ ] Construct buffers
- [ ] `WriteView` and `ReadView`
- [ ] Decide how to nicely access process info from system call interface
- [ ] Serialize into buffer
- [ ] Deserialize out of buffer

**Comment by IsaacWoods** [comment]
Also need to decide how we move messages between the sending and receiving processes: a `memcpy` is probably better for small messages because modifying page tables is expensive, but obviously not the answer for reading a multi-gb file. Maybe we should have different underlying mechanisms depending on the size of the message?
