### ISSUE TITLE
Move to using multiboot2-elf64 and acpi libraries

### ISSUE THREAD

**Issue by IsaacWoods** [IsaacWoods/pebble#3]
To alleviate some maintenance burden, move to using the official `multiboot2-elf64` and `acpi` libraries. This also allows us to use Pebble as a sort-of-testing framework for `acpi` (until we get real tests working)

To get back to where we were functionality wise:
- [x] Move to using `multiboot2` crate for parsing Multiboot header
- [ ] Add support for framebuffer tags to `multiboot2`
- [ ] Land changes to getting section names in `multiboot2` when we don't have identity mapping
- [ ] Get RSDP and framebuffer tags upstreamed and deployed on `multiboot2`
- [ ] Move to using the `acpi` crate for parsing ACPI tables
- [ ] Make sure `acpi` can actually parse and validate QEMU's tables correctly
- [ ] Parse the MADT in `acpi` and actually pass the information back correctly
- [ ] Use that information to configure the APICs again
